# Plugin made by BadBones69
# Spigot Page: https://www.spigotmc.org/resources/category-warps.12696/

settings:
    per-permissions:
        warp: true
        category: true
    timers:
        delay: 3 # How long should it take the user to wait to warp.
        cooldown: 30 # How long should it take until the user can warp again.

messages:
    prefix: '&0[&cWarp&0]&7'
    warp-success: '&7You are now warping to &6&l%Warp% &7in &c&l%Delay% &7Seconds.'
    warp-canceled: '&cTeleport cancelled due to you moving!'

cosmetics:
    per-warp-effects: true # Should each warp use independent particle effects from each other?
    per-warp-sounds: true  # Should each warp use independent sound effects from each other?
    global-particles: # If enabled, global takes priority over independent particle effects. Set to false if you want independent particle effects.
        enabled: false
        amount: 0
        effect: SMOKE
        x-offset: 1.0
        y-offset: 1.0
        z-offset: 1.0
        speed: 0.5
    global-sounds: # If enabled, global takes priority over independent sound effects. Set to false if you want independent sound effects.
        enabled: false
        sound: NOTEBLOCK
        volume: 1.0
        pitch: 1.0