name: ${artifactId}
main: com.badbones69.crazywarps.CrazyWarps
version: ${version}
authors: [BadBones69, apt.int]
softdepend: [Essentials, EssentialsX]
description: A clean, fancy and feature-rich warp plugin for your Minecraft Server!

commands:
  crazywarps:
    aliases: [cw, warp, warps]
    description: Base CrazyWarps command for users.
  crazywarpsadmin:
    aliases: [cwa, warpadmin, warpsadmin]
    description: Base CrazyWarps command for administrators.

    # Test Commit