name: "CrazyWarps"

main: "${group}.CrazyWarps"

authors: [BadBones69, apt.int]

version: ${version}
api-version: "1.19"
description: ${description}

softdepend:
  - Essentials
  - EssentialsX

commands:
  crazywarps:
    aliases: [cw, warp, warps]
    description: Base CrazyWarps command for users.

  crazywarpsadmin:
    aliases: [cwa, warpadmin, warpsadmin]
    description: Base CrazyWarps command for administrators.